---
layout: page
title: ""
---

<div style="display: flex; justify-content: space-between; align-items: flex-start; margin-bottom: 20px;">
  <!-- Right Side (Photo, Contact Info, and Social Links) -->
  <div style="text-align: center; flex: 0 0 250px;">
    <!-- Photo Section -->
    <img src="/files/Yue_Zhengjun.jpg" alt="Zhengjun" style="width: 100%; max-width: 200px; border-radius: 50%; margin-bottom: 20px; float: right; margin-left: 5px;">
    
    <!-- Contact Info Section -->
    <div style="font-size: 1rem; margin-bottom: 20px;">
      <p><strong>Email:</strong> <a href="mailto:z.yue@tudelft.nl">z.yue@tudelft.nl</a></p>
      <p><strong>Phone:</strong> +44 (0)75 4409 5405</p>
      <p><strong>LinkedIn:</strong> <a href="https://www.linkedin.com/in/zhengjun-yue/" target="_blank">Zhengjun Yue</a></p>
    </div>
    
    <!-- Social Media Icons Section -->
    <div style="font-size: 1.5rem;">
      <a href="mailto:z.yue@tudelft.nl" style="margin: 0 10px;"><i class="fa fa-envelope"></i></a>
      <a href="https://scholar.google.com/citations?hl=en&user=5_TTTUMAAAAJ" target="_blank" style="margin: 0 10px;"><i class="fa fa-google"></i></a>
      <a href="https://www.researchgate.net/profile/Zhengjun-Yue" target="_blank" style="margin: 0 10px;"><i class="fa fa-researchgate"></i></a>
      <a href="https://www.linkedin.com/in/zhengjun-yue/" target="_blank" style="margin: 0 10px;"><i class="fa fa-linkedin"></i></a>
      <a href="https://github.com/zhengjunyue" target="_blank" style="margin: 0 10px;"><i class="fa fa-github"></i></a>
      <a href="https://twitter.com/ZhengjunYue" target="_blank" style="margin: 0 10px;"><i class="fa fa-twitter"></i></a>
      <a href="https://orcid.org/my-orcid?orcid=0000-0002-1101-549X" target="_blank" style="margin: 0 10px;"><i class="fa fa-orcid"></i></a>
      <a href="https://www.facebook.com/profile.php?id=100021335133289" target="_blank" style="margin: 0 10px;"><i class="fa fa-facebook"></i></a>
      <a href="https://www.youtube.com/@ZhengjunYue/playlists" target="_blank" style="margin: 0 10px;"><i class="fa fa-youtube"></i></a>
    </div>
  </div>

  <!-- Left Side (Text) -->
  <div style="flex: 1; padding-left: 20px;">
    <h2>Short Bio</h2>
    <p>Greetings! I am an Assistant Professor at the Speech Lab of the Multimedia Computing Group at the Delft University of Technology (TU Delft), the Netherlands. My research focus is **Speech Technology for Healthcare**.</p>
    
    <p>I completed my PhD in the area of dysarthric speech recognition in the Speech and Hearing Group at the University of Sheffield, United Kingdom, funded by the Marie-Curie H2020 TAPAS project. After my PhD, I worked at King's College London (KCL), United Kingdom, as a postdoc funded by the British Engineering and Natural Sciences Research Council (EPSRC) SpeechWave project, focusing on robust dysarthric speech recognition using raw waveform acoustic modelling. I hold an M.Sc. in Artificial Intelligence from the University of Edinburgh and a B.Sc. in Telecommunication Engineering from Shanghai University. For more details, please visit my [CV](https://zhengjunyue.github.io/cv/) page.</p>
    
    <p>Outside of work, I enjoy dancing, singing, playing various instruments, and learning languages.</p>
  </div>
</div>

## Research Interests ##
* Speech Technology for Healthcare Applications
* Pathological speech processing and recognition
* Cognitive impairment detection and invention
* Child speech analysis
* Conversational AI medical systems for healthcare
* Multi-modal biomarkers for pathological speech
* Generative AI for pathological speech

## News ##
