title: "Zhengjun Yue"
author: "Zhengjun Yue"
description: ""
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_social: true          # show site description and social links in the footer
show_excerpts: false       # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_description: false    # show site description in the side bar
show_sidebar: false        # show a sidebar instead of the usual header
show_title: true
bib_search: true

# Styling

dark_header: false
minimal: false              # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
 # - {title: "Home", file: "about.md"}  # Set "about" layout for Home link
 # - {title: "Home", url: "/", icon: home}  # Update the URL to the homepage
 # - {title: "About", file: "/about.md"}
  - {title: "CV", url: "/cv"}
  - {title: "Publications", file: "publications.md"}
  - {title: "Teaching", file: "teaching.md"}
  - {title: "Activities", file: "activities.md"}
  - {title: "News", file: "news.md"}
  - {title: "Hobbies", file: "hobbies.md"}
  


external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:z.yue@tudelft.nl"}
  - {title: Google Scholar, icon: google, url: "https://scholar.google.com/citations?hl=en&user=5_TTTUMAAAAJ"}
  - {title: Research Gate, icon: researchgate, url: "https://www.researchgate.net/profile/Zhengjun-Yue"}
  - {title: LinkedIn, icon: linkedin, url: "https://www.linkedin.com/in/zhengjun-yue/"}
  - {title: Github, icon: github, url: "https://github.com/zhengjunyue"}
  - {title: Twitter, icon: twitter, url: "https://twitter.com/ZhengjunYue"}
  - {title: ORCiD, icon: orcid, url: "https://orcid.org/my-orcid?orcid=0000-0002-1101-549X"}
  - {title: Facebook, icon: facebook, url: "https://www.facebook.com/profile.php?id=100021335133289"}
  - {title: Youtube, icon: youtube, url: "https://www.youtube.com/@ZhengjunYue/playlists"}


comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed

# -----------------------------------------------------------------------------
# Jekyll Scholar
# -----------------------------------------------------------------------------

scholar:
  last_name: [Yue]
  first_name: [Zhengjun]

  style: apa
  locale: en

  source: /_bibliography/
  bibliography: papers.bib
  bibliography_template: bib
  # Note: if you have latex math in your bibtex, the latex filter
  # preprocessing may conflict with MathJAX if the latter is enabled.
  # See https://github.com/alshedivat/al-folio/issues/357.
  bibtex_filters: [latex, smallcaps, superscript]

  replace_strings: true
  join_strings: true

  details_dir: bibliography
  details_link: Details

  query: "@*"
  group_by: year
  group_order: descending

# Display different badges withs stats for your publications
# Customize badge behavior in _layouts/bib.liquid
enable_publication_badges:
  altmetric: true # Altmetric badge (Customization options: https://badge-docs.altmetric.com/index.html)
  dimensions: true # Dimensions badge (Customization options: https://badge.dimensions.ai/)
  google_scholar: true # Google Scholar badge (https://scholar.google.com/intl/en/scholar/citations.html)
  inspirehep: true # Inspire HEP badge (https://help.inspirehep.net/knowledge-base/citation-metrics/)

# Filter out certain bibtex entry keywords used internally from the bib output
filtered_bibtex_keywords:
  [
    abbr,
    abstract,
    additional_info,
    altmetric,
    annotation,
    arxiv,
    award,
    award_name,
    bibtex_show,
    blog,
    code,
    google_scholar_id,
    html,
    inspirehep_id,
    pdf,
    poster,
    preview,
    selected,
    slides,
    supp,
    video,
    website,
  ]

# Maximum number of authors to be shown for each publication (more authors are visible on click)
max_author_limit: 3 # leave blank to always show all authors
more_authors_animation_delay: 10 # more authors are revealed on click using animation; smaller delay means faster animation

# Enables publication thumbnails. If disabled, none of the publications will display thumbnails, even if specified in the bib entry.
enable_publication_thumbnails: true
